import { useMemo, useRef, useState } from 'react';
import { Bot, ImagePlus, Mic, RefreshCw, Send, Settings2, Sparkles, UserRound } from 'lucide-react';
import type { CosmeticItem, FoodItem, InventoryItem } from '../lib/types';
import { put } from '../lib/db';
import { getExpiryStatus } from '../lib/date';
import { Button, Card } from '../components/ui';

export type ChatMessage = { id:string; role:'user'|'ai'; content:string; ts:number; profileId?:string; isError?:boolean; retryFor?:string };

export function ChatPage({ messages, foods, inventory, cosmetics, apiKey, model, profileId, onSettings, onChange }: { messages:ChatMessage[];foods:FoodItem[];inventory:InventoryItem[];cosmetics:CosmeticItem[];apiKey:string;model:string;profileId:string;onSettings:()=>void;onChange:()=>void }) { const [draft,setDraft]=useState('');const [busy,setBusy]=useState(false);const [image,setImage]=useState<string|null>(null);const inputRef=useRef<HTMLInputElement>(null);const context=useMemo(()=>buildContext(foods,inventory,cosmetics),[foods,inventory,cosmetics]);if(!apiKey)return <div className="page-container chat-page"><div className="chat-empty-state"><div className="chat-logo"><Bot size={32}/></div><h2>Your household copilot</h2><p>Ask about expiry, high-protein meals or what you can cook with what you have. Add your OpenRouter key to begin.</p><Button onClick={onSettings}><Settings2 size={16}/> Set up AI</Button></div></div>;
  const send=async(text?:string,retryMessage?:ChatMessage)=>{const content=(text??draft).trim()|| (image?'Identify this household item from the attached photo.':'');if(!content||busy)return;setDraft('');setBusy(true);const user=retryMessage||{id:`msg_${Date.now()}`,role:'user' as const,content,ts:Date.now(),profileId};if(!retryMessage)await put('chat_messages',user);onChange();try{const history: {role:'user'|'assistant';content:unknown}[]=[...messages.filter((message)=>message.id!==retryMessage?.id),user].slice(-10).map((message)=>({role:message.role==='user'?'user':'assistant',content:message.content}));if(image&&history.length)history[history.length-1]={role:'user',content:[{type:'text',text:content},{type:'image_url',image_url:{url:image}}]};const response=await fetch('https://openrouter.ai/api/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json','HTTP-Referer':window.location.href,'X-Title':'GharApp React'},body:JSON.stringify({model:model||'openrouter/free',messages:[{role:'system',content:`You are GharApp, a concise and kind Indian household assistant. Reply naturally in the user's Hindi/English mix. Use this private household context when relevant. If a question is outside it, give general guidance and say so.\n\n${context}`},...history]})});let body:Record<string,unknown>={};try{body=await response.json()}catch{}if(!response.ok)throw new Error(String((body.error as {message?:string}|undefined)?.message||`Request failed (${response.status})`));const reply=String(((body.choices as {message?:{content?:string}}[]|undefined)?.[0]?.message?.content)||'No response received.');await put('chat_messages',{id:`msg_${Date.now()}_ai`,role:'ai',content:reply,ts:Date.now(),profileId});setImage(null);onChange()}catch(error){await put('chat_messages',{id:`msg_${Date.now()}_error`,role:'ai',content:`${error instanceof Error?error.message:'Network error'} — please check your key or connection.`,ts:Date.now(),profileId,isError:true,retryFor:user.id});onChange()}finally{setBusy(false)}};
  return <div className="page-container chat-page"><div className="chat-intro"><div className="chat-title"><span className="chat-logo"><Bot size={21}/></span><div><span className="eyebrow">PRIVATE ASSISTANT</span><h2>Ask GharApp</h2></div></div><span className="online-pill"><i/> {model==='openrouter/free'?'Auto model':'AI ready'}</span></div><div className="chat-quick-row"><button type="button" onClick={()=>send("What's expiring soon?")}>⏰ Expiring soon</button><button type="button" onClick={()=>send('Suggest a high protein dinner')}>💪 High protein</button><button type="button" onClick={()=>send('What can I cook with my ingredients?')}>🍳 What can I cook?</button></div><div className="chat-messages">{messages.length?messages.map((message)=><div className={`message ${message.role==='user'?'message-user':'message-ai'}`} key={message.id}><span className="message-avatar">{message.role==='user'?<UserRound size={14}/>:<Bot size={14}/>}</span><div><p>{message.content}</p>{message.isError&&<button type="button" className="retry-link" onClick={()=>{const original=messages.find((item)=>item.id===message.retryFor);if(original)send(original.content,original)}}><RefreshCw size={13}/> Retry</button>}</div></div>):<div className="chat-welcome"><Sparkles size={20}/><p>Try asking: “mere paas kya expire hone wala hai?”</p></div>}{busy&&<div className="message message-ai"><span className="message-avatar"><Bot size={14}/></span><div className="typing"><i/><i/><i/></div></div>}</div><div className="chat-composer">{image&&<div className="attachment-pill">Image attached <button type="button" onClick={()=>setImage(null)}>×</button></div>}<div className="composer-row"><button type="button" className="composer-icon" onClick={()=>{const browserWindow=window as typeof window & {SpeechRecognition?:new()=>any;webkitSpeechRecognition?:new()=>any};const Speech=browserWindow.SpeechRecognition||browserWindow.webkitSpeechRecognition;if(!Speech)return;const recognition=new Speech();recognition.lang='hi-IN';recognition.onresult=(event:any)=>setDraft((value)=>`${value} ${event.results[0][0].transcript}`.trim());recognition.start()}} aria-label="Voice input"><Mic size={17}/></button><label className="composer-icon" aria-label="Attach image"><ImagePlus size={17}/><input type="file" accept="image/*" capture="environment" onChange={async(event)=>{const file=event.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>setImage(String(reader.result));reader.readAsDataURL(file)}}/></label><input ref={inputRef} value={draft} onChange={(event)=>setDraft(event.target.value)} onKeyDown={(event)=>{if(event.key==='Enter')send()}} placeholder="Ask in Hindi, English or Hinglish…"/><button type="button" className="send-button" onClick={()=>send()} disabled={busy}><Send size={17}/></button></div></div></div>;
}
function buildContext(foods:FoodItem[],inventory:InventoryItem[],cosmetics:CosmeticItem[]){const stock=inventory.slice().sort((a,b)=>String(a.expiryDate||'9999').localeCompare(String(b.expiryDate||'9999'))).slice(0,60).map((item)=>`- ${item.name}, ${item.quantity} ${item.unit}, expiry ${item.expiryDate||'unknown'} (${getExpiryStatus(item.expiryDate,item.alertBeforeDays)})`).join('\n')||'none';const food=foods.slice(0,80).map((item)=>`- ${item.name}: ${item.caloriesPer100g||0} kcal, P ${item.proteinPer100g||0}g, tags ${(item.tags||[]).join(', ')}`).join('\n');return `Current inventory:\n${stock}\n\nCosmetics:\n${cosmetics.map((item)=>`- ${item.name}, expiry ${item.expiryDate||'unknown'} (${getExpiryStatus(item.expiryDate,item.alertBeforeDays)})`).join('\n')||'none'}\n\nFood reference:\n${food}`}
