import { useMemo, useState } from 'react';
import { CalendarDays, ChevronLeft, ChevronRight, Plus, Trash2 } from 'lucide-react';
import type { FoodItem, MealPlanItem } from '../lib/types';
import { addDaysISO, formatDate, todayISO } from '../lib/date';
import { put, remove } from '../lib/db';
import { normalizeFood, round2 } from '../lib/normalize';
import { Button, Card, Field, Modal } from '../components/ui';

const slots: { key: MealPlanItem['slot']; label: string; icon: string }[] = [{ key: 'breakfast', label: 'Breakfast', icon: '🌅' }, { key: 'lunch', label: 'Lunch', icon: '☀️' }, { key: 'dinner', label: 'Dinner', icon: '🌙' }, { key: 'snack', label: 'Snacks', icon: '🍎' }];

export function PlannerPage({ date, foods, plans, profileId, onDateChange, onChange, onOpenTracker }: { date: string; foods: FoodItem[]; plans: MealPlanItem[]; profileId: string; onDateChange: (date: string) => void; onChange: () => void; onOpenTracker: () => void }) {
  const [addSlot, setAddSlot] = useState<MealPlanItem['slot'] | null>(null);
  const [showWeek, setShowWeek] = useState(false);
  const foodMap = useMemo(() => new Map(foods.map((food) => [food.id, normalizeFood(food)])), [foods]);
  const total = plans.reduce((sum, plan) => { const food=foodMap.get(plan.foodId); const factor=(plan.quantity||100)/100; return { calories: sum.calories + Number(food?.caloriesPer100g||0)*factor, protein: sum.protein + Number(food?.proteinPer100g||0)*factor, carbs: sum.carbs + Number(food?.carbsPer100g||0)*factor, fat: sum.fat + Number(food?.fatPer100g||0)*factor }; }, { calories: 0, protein: 0, carbs: 0, fat: 0 });
  return <div className="page-container planner-page"><div className="module-heading"><div><span className="eyebrow">PLAN AHEAD</span><h2>Meal planner</h2><p>Build a calm week around food you already like.</p></div><button type="button" className="round-control" onClick={()=>setShowWeek(!showWeek)} aria-label="Toggle week view"><CalendarDays size={17}/></button></div><div className="date-navigator"><button type="button" onClick={()=>onDateChange(addDaysISO(-1,new Date(`${date}T00:00:00`)))}><ChevronLeft size={17}/></button><div><span>{formatDate(date)}</span><strong>{date===todayISO()?'Today':'Your plan'}</strong></div><button type="button" onClick={()=>onDateChange(addDaysISO(1,new Date(`${date}T00:00:00`)))}><ChevronRight size={17}/></button></div>{showWeek&&<WeekStrip selected={date} onSelect={onDateChange}/>}<Card className="plan-summary"><div><span className="eyebrow">DAY TOTAL</span><h3>{Math.round(total.calories)} <small>kcal</small></h3></div><div className="summary-metrics"><span><b>{round2(total.protein)}g</b> protein</span><span><b>{round2(total.carbs)}g</b> carbs</span><span><b>{round2(total.fat)}g</b> fat</span></div></Card>{slots.map((slot)=><section className="meal-slot" key={slot.key}><div className="slot-header"><div><span>{slot.icon}</span><strong>{slot.label}</strong></div><button type="button" className="add-inline" onClick={()=>setAddSlot(slot.key)}><Plus size={14}/> Add</button></div>{plans.filter((plan)=>plan.slot===slot.key).length?plans.filter((plan)=>plan.slot===slot.key).map((plan)=><PlanRow key={plan.id} plan={plan} food={foodMap.get(plan.foodId)} onDelete={async()=>{await remove('meal_plans',plan.id);onChange()}}/>):<div className="slot-empty">Nothing planned yet</div>}</section>)}<Button variant="secondary" onClick={onOpenTracker}>Track today’s intake →</Button>{addSlot&&<AddMealModal slot={addSlot} date={date} foods={foods} profileId={profileId} onClose={()=>setAddSlot(null)} onSaved={()=>{setAddSlot(null);onChange()}}/>}</div>;
}
function WeekStrip({selected,onSelect}:{selected:string;onSelect:(date:string)=>void}){const center=new Date(`${selected}T00:00:00`);return <div className="week-strip">{Array.from({length:7},(_,index)=>{const date=new Date(center);date.setDate(center.getDate()+index-3);const iso=date.toISOString().slice(0,10);return <button type="button" key={iso} className={iso===selected?'active':''} onClick={()=>onSelect(iso)}><small>{date.toLocaleDateString('en-IN',{weekday:'short'})}</small><strong>{date.getDate()}</strong></button>})}</div>}
function PlanRow({plan,food,onDelete}:{plan:MealPlanItem;food?:FoodItem;onDelete:()=>void}){const kcal=Math.round(Number(food?.caloriesPer100g||0)*(plan.quantity||100)/100);return <div className="plan-row"><span className="food-mini-icon">🥗</span><div><strong>{food?.name||'Unknown food'}</strong><small>{plan.quantity}g · {kcal} kcal · P {round2(Number(food?.proteinPer100g||0)*(plan.quantity||100)/100)}g</small></div><button type="button" onClick={onDelete} aria-label="Remove meal"><Trash2 size={15}/></button></div>}
function AddMealModal({slot,date,foods,profileId,onClose,onSaved}:{slot:MealPlanItem['slot'];date:string;foods:FoodItem[];profileId:string;onClose:()=>void;onSaved:()=>void}){const [foodId,setFoodId]=useState(foods[0]?.id||'');const [quantity,setQuantity]=useState(100);const save=async()=>{if(!foodId)return;await put('meal_plans',{id:`meal_${Date.now()}_${Math.random().toString(36).slice(2,6)}`,profileId,date,slot,foodId,quantity,createdAt:new Date().toISOString()});onSaved()};return <Modal title={`Add to ${slot}`} description="Choose a food from your library." onClose={onClose}><Field label="Food item"><select value={foodId} onChange={(event)=>setFoodId(event.target.value)}>{foods.map((food)=><option key={food.id} value={food.id}>{food.name}</option>)}</select></Field><Field label="Quantity in grams"><input type="number" min={1} value={quantity} onChange={(event)=>setQuantity(Number(event.target.value))}/></Field><Button size="lg" onClick={save}>Add to plan</Button></Modal>}
