import { useState } from 'react';
import { Camera, FileText, Sparkles, Upload } from 'lucide-react';
import type { InventoryItem } from '../lib/types';
import { normalizeInventory } from '../lib/normalize';
import { Button, Card, Field, Modal } from '../components/ui';

type ReceiptDraft = { name: string; brand?: string; category?: string; quantity?: number; unit?: string; price?: number; expiryDate?: string };

/** Receipt-to-inventory flow. Vision is optional; manual lines remain available offline. */
export function ReceiptScanner({ apiKey, model, profileId, onClose, onSaved }: { apiKey: string; model: string; profileId: string; onClose: () => void; onSaved: (items: InventoryItem[]) => void }) {
  const [image,setImage]=useState<string|null>(null);const [drafts,setDrafts]=useState<ReceiptDraft[]>([]);const [manual,setManual]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('Upload a receipt photo. The image is sent only when you tap Extract.');
  const parseManual=()=>manual.split('\n').map((line)=>line.trim()).filter(Boolean).map((line)=>{const [name,quantity,unit,expiryDate,price]=line.split(',').map((part)=>part.trim());return {name,quantity:Number(quantity)||1,unit:unit||'pcs',expiryDate:expiryDate||'',price:Number(price)||0}}).filter((item)=>item.name);
  const extract=async()=>{if(!image)return setMessage('Receipt photo select karein.');if(!apiKey)return setMessage('AI key missing. Neeche manual format use karein: Name, quantity, unit, expiry, price');setBusy(true);setMessage('AI receipt scan kar raha hai…');try{const response=await fetch('https://openrouter.ai/api/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({model:model||'openrouter/free',temperature:.1,max_tokens:900,messages:[{role:'system',content:'You extract grocery receipts. Return only valid JSON, no markdown: {"items":[{"name":"","brand":"","category":"Groceries","quantity":1,"unit":"pcs","price":0,"expiryDate":""}]}. Use empty strings when a field is not visible. Do not invent expiry dates.'},{role:'user',content:[{type:'text',text:'Read this receipt and extract every purchasable household item into JSON.'},{type:'image_url',image_url:{url:image}}]}]})});const json=await response.json() as {choices?:{message?:{content?:string}}[];error?:{message?:string}};if(!response.ok)throw new Error(json.error?.message||`Request failed (${response.status})`);const content=json.choices?.[0]?.message?.content||'';const match=content.match(/\{[\s\S]*\}/);if(!match)throw new Error('AI returned no item list');const parsed=JSON.parse(match[0]) as {items?:ReceiptDraft[]};setDrafts((parsed.items||[]).filter((item)=>item.name));setMessage(`${parsed.items?.length||0} items found. Review and import.`)}catch(error){setMessage(error instanceof Error?error.message:'Receipt extraction failed. Try manual lines.')}finally{setBusy(false)}};
  const importItems=()=>{const items=(drafts.length?drafts:parseManual()).map((item,index)=>normalizeInventory({...item,id:`receipt_${Date.now()}_${index}`,profileId,source:'Receipt scan',status:'unopened',createdAt:new Date().toISOString()},profileId));if(!items.length)return setMessage('At least one item add karein.');onSaved(items)};
  return <Modal title="Receipt → inventory" description="Photo se items extract karein, review karein, then save." onClose={onClose} wide><label className="receipt-upload">{image?<img src={image} alt="Receipt preview"/>:<><Camera size={26}/><strong>Take or upload receipt photo</strong><small>AI extraction is optional</small></>}<input type="file" accept="image/*" capture="environment" onChange={(event)=>{const file=event.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>setImage(String(reader.result));reader.readAsDataURL(file)}}/></label><p className="receipt-message"><Sparkles size={14}/>{message}</p><Button onClick={extract} disabled={!image||busy}>{busy?'Extracting…':'Extract items with AI'}</Button>{drafts.length>0&&<div className="receipt-results"><div className="filter-label"><span>Review items</span><small>{drafts.length} found</small></div>{drafts.map((item,index)=><Card className="receipt-item" key={`${item.name}-${index}`}><FileText size={15}/><div><strong>{item.name}</strong><small>{item.quantity||1} {item.unit||'pcs'}{item.price?` · ₹${item.price}`:''}{item.expiryDate?` · Exp ${item.expiryDate}`:''}</small></div></Card>)}</div>}<Field label="Offline/manual fallback" hint="one item per line: Name, qty, unit, expiry, price"><textarea value={manual} onChange={(event)=>setManual(event.target.value)} placeholder={'Rajma, 500, g, 2027-01-01, 90\nAtta, 2, kg, , 140'}/></Field><Button variant="soft" onClick={()=>setDrafts(parseManual())}><Upload size={15}/> Parse manual lines</Button><Button variant="secondary" onClick={importItems}>Save items to inventory</Button></Modal>;
}
