import { useState } from 'react';
import { Check, CirclePlus, ListChecks, ShoppingCart, Sparkles, Trash2 } from 'lucide-react';
import type { InventoryItem, ShoppingItem } from '../lib/types';
import { put, remove } from '../lib/db';
import { Button, Card, EmptyState } from '../components/ui';

export function ShoppingPage({ items, inventory, profileId, onChange }: { items: ShoppingItem[]; inventory: InventoryItem[]; profileId: string; onChange: () => void }) {
  const [name, setName] = useState('');
  const active = items.filter((item) => !item.completed); const complete = items.filter((item) => item.completed);
  const lowStock = inventory.filter((item) => item.reorderLevel && item.quantity <= item.reorderLevel);
  const autoCount = lowStock.filter((item) => !active.some((shop) => shop.inventoryId === item.id)).length;
  const addManual = async () => { if(!name.trim())return; await put('shopping_items',{id:`shop_${Date.now()}`,profileId,name:name.trim(),source:'manual',completed:false,createdAt:new Date().toISOString()});setName('');onChange(); };
  const generate = async () => { const existing=new Set(active.map((item)=>item.name.toLowerCase()));for(const item of lowStock){if(!existing.has(item.name.toLowerCase()))await put('shopping_items',{id:`auto_${item.id}`,profileId,name:item.name,quantity:`${item.reorderLevel} ${item.unit}`,source:'auto',inventoryId:item.id,completed:false,createdAt:new Date().toISOString()});}onChange(); };
  return <div className="page-container shopping-page"><div className="module-heading"><div><span className="eyebrow">RESTOCK</span><h2>Shopping list</h2><p>Everything you need, nothing you forget.</p></div><div className="shopping-count"><ShoppingCart size={16}/><strong>{active.length}</strong></div></div><Card className="shopping-hero"><div className="shopping-hero-icon"><Sparkles size={22}/></div><div><strong>{autoCount ? `${autoCount} low-stock suggestions` : 'Your home is well stocked'}</strong><p>{autoCount ? 'Generate a smart list from your reorder levels.' : 'Keep adding reorder levels to automate this.'}</p></div><Button size="sm" onClick={generate}>{autoCount ? 'Generate' : 'Refresh'}</Button></Card><div className="add-shopping"><input value={name} onChange={(event)=>setName(event.target.value)} onKeyDown={(event)=>{if(event.key==='Enter')addManual()}} placeholder="Add an item…" aria-label="Add shopping item"/><Button onClick={addManual}><CirclePlus size={16}/> Add</Button></div><div className="shopping-section"><div className="section-heading"><div><span className="eyebrow">TO BUY</span><h3>{active.length} items</h3></div></div>{active.length?active.map((item)=><ShoppingRow item={item} key={item.id} onToggle={async()=>{await put('shopping_items',{...item,completed:true});onChange()}} onDelete={async()=>{await remove('shopping_items',item.id);onChange()}}/>):<EmptyState icon={<ListChecks size={27}/>} title="List is clear" description="Add items manually or generate from low stock."/>}</div>{complete.length>0&&<div className="shopping-section"><div className="section-heading"><div><span className="eyebrow">DONE</span><h3>{complete.length} completed</h3></div><button type="button" className="text-button" onClick={async()=>{for(const item of complete)await remove('shopping_items',item.id);onChange()}}>Clear done</button></div>{complete.map((item)=><ShoppingRow item={item} key={item.id} onToggle={async()=>{await put('shopping_items',{...item,completed:false});onChange()}} onDelete={async()=>{await remove('shopping_items',item.id);onChange()}} completed/>)}</div>}</div>;
}
function ShoppingRow({item,onToggle,onDelete,completed=false}:{item:ShoppingItem;onToggle:()=>void;onDelete:()=>void;completed?:boolean}){return <Card className={`shopping-row ${completed?'completed':''}`}><button type="button" className={`check-button ${completed?'checked':''}`} onClick={onToggle} aria-label={completed?'Mark incomplete':'Mark complete'}>{completed?<Check size={15}/>:null}</button><div><strong>{item.name}</strong><small>{item.source==='auto'?'Smart suggestion':'Added by you'}{item.quantity?` · ${item.quantity}`:''}</small></div><button type="button" className="delete-button" onClick={onDelete} aria-label="Delete item"><Trash2 size={15}/></button></Card>}
