import { useMemo, useState } from 'react';
import { Bookmark, Check, ChevronDown, RotateCcw, Save, Search, Trash2, X } from 'lucide-react';
import { BEST_TIMES, COSMETIC_CATEGORIES, INV_STATUSES, INVENTORY_CATEGORIES, SKIN_TYPES, TASTES, SEASONS, type CosmeticItem, type FilterState, type FoodItem, type FoodMode, type InventoryItem, type LocationItem, type ModuleName, type SavedFilter } from '../lib/types';
import { Modal, Button, Chip, Field } from './ui';

type Tone = 'mint' | 'purple' | 'blue';
type Section = 'discover' | 'nutrition' | 'goals' | 'advanced';

function listValue(filters: FilterState, key: string): string[] { const value=filters[key];return Array.isArray(value)?value.map(String):[]; }
function activeCount(filters: FilterState): number { return Object.entries(filters).filter(([key,value])=>key!=='sort'&&value!==undefined&&value!==''&&value!==false&&(!Array.isArray(value)||value.length>0)).length; }
function unique(values: (string|undefined)[]): string[] { return [...new Set(values.filter(Boolean) as string[])].sort((a,b)=>a.localeCompare(b)); }
function filterText(value: unknown): string { return String(value??'').toLowerCase(); }

function OptionCluster({title,options,value,onChange,tone,labels={},search,limit=28,defaultOpen=false}:{title:string;options:string[];value:string[];onChange:(next:string[])=>void;tone:Tone;labels?:Record<string,string>;search:string;limit?:number;defaultOpen?:boolean}) {
  const filtered=options.filter((option)=>!search||filterText(labels[option]??option).includes(search.toLowerCase()));
  const visible=search?filtered:filtered.slice(0,limit);
  return <details className="filter-accordion" open={defaultOpen}><summary><span>{title}</span><small>{value.length?`${value.length} selected`:'Tap to expand'}</small><ChevronDown size={14}/></summary><div className="accordion-content"><div className="option-grid">{visible.map((option)=>{const selected=value.some((item)=>item.toLowerCase()===option.toLowerCase());return <button type="button" key={option} className={`option-pill ${selected?`selected ${tone}`:''}`} onClick={()=>onChange(selected?value.filter((item)=>item.toLowerCase()!==option.toLowerCase()):[...value,option])} aria-pressed={selected}>{selected&&<Check size={13}/>} {labels[option]??option}</button>})}</div>{filtered.length>visible.length&&<small className="more-options">+{filtered.length-visible.length} more — use “Search filter options” above</small>}</div></details>;
}
function RangePair({label,min,max,minKey,maxKey,filters,onChange,step=1}:{label:string;min:number;max:number;minKey:string;maxKey:string;filters:FilterState;onChange:(key:string,value:number|undefined)=>void;step?:number}) { const from=Number(filters[minKey]??min),to=Number(filters[maxKey]??max);return <div className="range-group"><div className="filter-label"><span>{label}</span><small>{from===min&&to===max?'Any':`${from} – ${to}`}</small></div><div className="range-sliders"><input type="range" min={min} max={max} step={step} value={Math.min(from,to)} onChange={(event)=>onChange(minKey,Number(event.target.value))}/><input type="range" min={min} max={max} step={step} value={Math.max(from,to)} onChange={(event)=>onChange(maxKey,Number(event.target.value))}/></div><div className="range-inputs"><input type="number" min={min} max={max} step={step} placeholder="Min" value={filters[minKey]==null?'':String(filters[minKey])} onChange={(event)=>onChange(minKey,event.target.value===''?undefined:Number(event.target.value))}/><input type="number" min={min} max={max} step={step} placeholder="Max" value={filters[maxKey]==null?'':String(filters[maxKey])} onChange={(event)=>onChange(maxKey,event.target.value===''?undefined:Number(event.target.value))}/></div></div>; }
function DateRange({label,prefix,filters,onChange}:{label:string;prefix:string;filters:FilterState;onChange:(key:string,value:string|undefined)=>void}) { return <div className="date-range"><span className="filter-label">{label}</span><input type="date" value={String(filters[`${prefix}From`]??'')} onChange={(event)=>onChange(`${prefix}From`,event.target.value||undefined)}/><span>to</span><input type="date" value={String(filters[`${prefix}To`]??'')} onChange={(event)=>onChange(`${prefix}To`,event.target.value||undefined)}/></div>; }

function SectionTabs({section,setSection}: {section:Section;setSection:(section:Section)=>void}) { const tabs:[Section,string,string][]=[['discover','01','Discover'],['nutrition','02','Nutrition'],['goals','03','Goals'],['advanced','04','Advanced']];return <div className="filter-tabs" role="tablist">{tabs.map(([key,number,label])=><button type="button" key={key} className={section===key?'active':''} onClick={()=>setSection(key)} role="tab" aria-selected={section===key}><span>{number}</span>{label}</button>)}</div>; }

export function FilterSheet({module,foodMode='raw',filters,items,locations,saved,onApply,onClose,onSave,onDeleteSaved,onUseSaved}:{module:ModuleName;filters:FilterState;foodMode?:FoodMode;items:(FoodItem|InventoryItem|CosmeticItem)[];locations:LocationItem[];saved:SavedFilter[];onApply:(filters:FilterState)=>void;onClose:()=>void;onSave:(name:string,filters:FilterState)=>void;onDeleteSaved:(id:string)=>void;onUseSaved:(filter:SavedFilter)=>void}) {
  const [draft,setDraft]=useState<FilterState>({...filters});const [section,setSection]=useState<Section>('discover');const [search,setSearch]=useState('');const [saveName,setSaveName]=useState('');
  const update=(key:string,value:FilterState[string])=>setDraft((current)=>{const next={...current};if(value===undefined||value===''||(Array.isArray(value)&&!value.length))delete next[key];else next[key]=value;return next});const toggle=(key:string)=>(next:string[])=>update(key,next);
  const food=items as FoodItem[],inventory=items as InventoryItem[],cosmetics=items as CosmeticItem[];const sessionFoods=food.filter((item)=>item.foodType===foodMode);const tone:Tone=module==='cosmetics'?'purple':module==='inventory'?'blue':'mint';const title=module==='food'?(foodMode==='cooked'?'Cooked meal filters':'Raw ingredient filters'):module==='inventory'?'Inventory smart filters':'Beauty shelf filters';
  const foodCategories=useMemo(()=>unique(sessionFoods.map((item)=>item.category)),[sessionFoods]);const subCategories=useMemo(()=>unique(sessionFoods.filter((item)=>!listValue(draft,'categories').length||listValue(draft,'categories').map((value)=>value.toLowerCase()).includes(item.category.toLowerCase())).map((item)=>item.subCategory)),[sessionFoods,draft]);const cuisines=useMemo(()=>unique(sessionFoods.map((item)=>item.cuisineStyle)),[sessionFoods]);const regions=useMemo(()=>unique(sessionFoods.flatMap((item)=>item.regions??[])),[sessionFoods]);const mealTypes=useMemo(()=>unique(sessionFoods.flatMap((item)=>item.mealTypes??[])),[sessionFoods]);const healthGoals=useMemo(()=>unique(sessionFoods.flatMap((item)=>item.goodForHealthGoals??[])),[sessionFoods]);const foodTags=useMemo(()=>unique(sessionFoods.flatMap((item)=>item.tags??[])),[sessionFoods]);const allergens=useMemo(()=>unique(sessionFoods.flatMap((item)=>[...(item.allergens??[]),...(item.allergenTags??[])])),[sessionFoods]);const cookingMethods=useMemo(()=>unique(sessionFoods.flatMap((item)=>item.preparationMethods??[])),[sessionFoods]);const locationLabels=Object.fromEntries(locations.map((location)=>[location.id,location.name]));
  const selectedSummary=Object.entries(draft).filter(([key,value])=>key!=='sort'&&value!==undefined&&value!==''&&value!==false).flatMap(([key,value])=>Array.isArray(value)?value.map((item)=>`${key}:${item}`):[`${key}:${String(value)}`]);
  return <Modal title={title} description={module==='food'?(foodMode==='cooked'?'Filter recipes, cuisines, meal type and cooked nutrition.':'Filter ingredients, produce, season and raw nutrition.'):'Search + every selected condition uses AND logic.'} onClose={onClose} wide><div className="filter-summary"><div><strong>{activeCount(draft)} active filters</strong><small>{selectedSummary.length?selectedSummary.slice(0,3).join(' · '):'Start with a category, cuisine or goal'}</small></div>{activeCount(draft)>0&&<button type="button" onClick={()=>setDraft({})}><RotateCcw size={13}/> Clear all</button>}</div><div className="filter-option-search"><Search size={15}/><input value={search} onChange={(event)=>setSearch(event.target.value)} placeholder="Search filter options…" aria-label="Search filter options"/>{search&&<button type="button" onClick={()=>setSearch('')}><X size={14}/></button>}</div><SectionTabs section={section} setSection={setSection}/><div className="filter-sheet-body">
    {module==='food'&&foodMode==='raw'&&section==='discover'&&<><OptionCluster title="Raw ingredient category" options={foodCategories} value={listValue(draft,'categories')} onChange={toggle('categories')} tone={tone} defaultOpen search={search}/><OptionCluster title="Ingredient sub-category" options={subCategories} value={listValue(draft,'subCategories')} onChange={toggle('subCategories')} tone={tone} search={search}/><OptionCluster title="Season & taste" options={[...SEASONS,...TASTES]} value={[...listValue(draft,'seasons'),...listValue(draft,'tastes')]} onChange={(next)=>{update('seasons',next.filter((value)=>SEASONS.includes(value)));update('tastes',next.filter((value)=>TASTES.includes(value)))}} tone={tone} search={search}/><OptionCluster title="Origin / region" options={regions} value={listValue(draft,'regions')} onChange={toggle('regions')} tone={tone} search={search}/><OptionCluster title="Preparation method" options={cookingMethods} value={listValue(draft,'preparationMethods')} onChange={toggle('preparationMethods')} tone={tone} search={search}/></>}
    {module==='food'&&foodMode==='cooked'&&section==='discover'&&<><OptionCluster title="Cuisine" options={cuisines} value={listValue(draft,'cuisines')} onChange={toggle('cuisines')} tone={tone} defaultOpen search={search}/><OptionCluster title="Dish type" options={foodCategories} value={listValue(draft,'categories')} onChange={toggle('categories')} tone={tone} search={search}/><OptionCluster title="Dish / recipe family" options={subCategories} value={listValue(draft,'subCategories')} onChange={toggle('subCategories')} tone={tone} search={search}/><OptionCluster title="Meal course" options={mealTypes.length?mealTypes:BEST_TIMES} value={listValue(draft,'mealTypes')} onChange={toggle('mealTypes')} tone={tone} search={search}/><OptionCluster title="Best time to eat" options={BEST_TIMES} value={listValue(draft,'bestTimes')} onChange={toggle('bestTimes')} tone={tone} search={search}/><OptionCluster title="Region / style" options={regions} value={listValue(draft,'regions')} onChange={toggle('regions')} tone={tone} search={search}/></>}

    {module==='food'&&section==='nutrition'&&<details className="filter-accordion" open><summary><span>Macro & GI ranges</span><small>per 100g</small><ChevronDown size={14}/></summary><div className="accordion-content"><RangePair label="Calories · kcal" min={0} max={900} minKey="minCalories" maxKey="maxCalories" filters={draft} onChange={update}/><RangePair label="Protein · g" min={0} max={60} minKey="minProtein" maxKey="maxProtein" filters={draft} onChange={update} step={.1}/><RangePair label="Carbs · g" min={0} max={100} minKey="minCarbs" maxKey="maxCarbs" filters={draft} onChange={update} step={.1}/><RangePair label="Fat · g" min={0} max={100} minKey="minFat" maxKey="maxFat" filters={draft} onChange={update} step={.1}/><RangePair label="Fiber · g" min={0} max={40} minKey="minFiber" maxKey="maxFiber" filters={draft} onChange={update} step={.1}/><RangePair label="Sugar · g" min={0} max={100} minKey="minSugar" maxKey="maxSugar" filters={draft} onChange={update} step={.1}/><RangePair label="Glycemic index" min={0} max={100} minKey="minGI" maxKey="maxGI" filters={draft} onChange={update}/></div></details>}
    {module==='food'&&section==='goals'&&<><OptionCluster title="Health goals" options={healthGoals} value={listValue(draft,'healthGoals')} onChange={toggle('healthGoals')} tone={tone} search={search}/><OptionCluster title="Dietary preferences" options={['Vegetarian','Vegan','Gluten-free','Jain','Contains egg']} value={['Vegetarian','Vegan','Gluten-free','Jain','Contains egg'].filter((item)=>draft[{Vegetarian:'isVeg',Vegan:'isVegan','Gluten-free':'isGlutenFree',Jain:'isJain','Contains egg':'isEgg'}[item] as string]===true)} onChange={(next)=>{const map:{[key:string]:string}={Vegetarian:'isVeg',Vegan:'isVegan','Gluten-free':'isGlutenFree',Jain:'isJain','Contains egg':'isEgg'};setDraft((old)=>{const copy={...old};Object.values(map).forEach((key)=>delete copy[key]);next.forEach((item)=>copy[map[item]]=true);return copy})}} tone={tone} search={search}/><OptionCluster title="Tags" options={foodTags} value={listValue(draft,'tags')} onChange={toggle('tags')} tone={tone} search={search}/><OptionCluster title="Allergens" options={allergens} value={listValue(draft,'allergens')} onChange={toggle('allergens')} tone={tone} search={search}/></>}
    {module==='food'&&section==='advanced'&&<><RangePair label="Cooking time · minutes" min={0} max={180} minKey="minCookingTime" maxKey="maxCookingTime" filters={draft} onChange={update}/><Field label="Specific pro"><select value={String(draft.prosText??'')} onChange={(event)=>update('prosText',event.target.value||undefined)}><option value="">Any pro</option>{unique(food.flatMap((item)=>item.pros??[])).map((pro)=><option key={pro}>{pro}</option>)}</select></Field><Field label="Specific con"><input value={String(draft.consText??'')} onChange={(event)=>update('consText',event.target.value||undefined)} placeholder="e.g. sugar"/></Field><div className="advanced-note">Nutrition data is per 100g. Restaurant-style dishes are curated India-available estimates.</div></>}
    {module==='inventory'&&section==='discover'&&<><OptionCluster title="Category" options={unique([...INVENTORY_CATEGORIES,...inventory.map((item)=>item.category)])} value={listValue(draft,'categories')} onChange={toggle('categories')} tone={tone} search={search}/><OptionCluster title="Storage location" options={locations.map((location)=>location.id)} labels={locationLabels} value={listValue(draft,'locationIds')} onChange={toggle('locationIds')} tone={tone} search={search}/><OptionCluster title="Status" options={[...INV_STATUSES]} value={listValue(draft,'statuses')} onChange={toggle('statuses')} tone={tone} search={search}/><OptionCluster title="Expiry status" options={['safe','near','expired']} value={listValue(draft,'expiryStatuses')} onChange={toggle('expiryStatuses')} tone={tone} search={search}/></>}
    {module==='inventory'&&section==='nutrition'&&<details className="filter-accordion" open><summary><span>Quantity & price</span><small>range</small><ChevronDown size={14}/></summary><div className="accordion-content"><RangePair label="Quantity" min={0} max={1000} minKey="minQuantity" maxKey="maxQuantity" filters={draft} onChange={update}/><RangePair label="Price · ₹" min={0} max={100000} minKey="minPrice" maxKey="maxPrice" filters={draft} onChange={update}/><div className="advanced-note">Set a reorder level on an item to include it automatically in Shopping list.</div></div></details>}
    {module==='inventory'&&section==='goals'&&<><OptionCluster title="Quick state" options={['Low stock','Has barcode','Has photo']} value={listValue(draft,'smartFlags')} onChange={toggle('smartFlags')} tone={tone} search={search}/><Field label="Source / shop"><input value={String(draft.sourceText??'')} onChange={(event)=>update('sourceText',event.target.value||undefined)} placeholder="e.g. DMart"/></Field></>}
    {module==='inventory'&&section==='advanced'&&<><div className="filter-section-title">Date ranges</div><DateRange label="Purchase date" prefix="purchase" filters={draft} onChange={update}/><DateRange label="MFG date" prefix="mfg" filters={draft} onChange={update}/><DateRange label="Expiry date" prefix="expiry" filters={draft} onChange={update}/></>}
    {module==='cosmetics'&&section==='discover'&&<><OptionCluster title="Category" options={unique([...COSMETIC_CATEGORIES,...cosmetics.map((item)=>item.category)])} value={listValue(draft,'categories')} onChange={toggle('categories')} tone={tone} search={search}/><OptionCluster title="Skin type" options={SKIN_TYPES} value={listValue(draft,'skinTypes')} onChange={toggle('skinTypes')} tone={tone} search={search}/><OptionCluster title="Opened state" options={['Opened','Unopened']} value={draft.opened===true?['Opened']:draft.opened===false?['Unopened']:[]} onChange={(next)=>update('opened',next[0]==='Opened'?true:next[0]==='Unopened'?false:undefined)} tone={tone} search={search}/><OptionCluster title="Expiry status" options={['safe','near','expired']} value={listValue(draft,'expiryStatuses')} onChange={toggle('expiryStatuses')} tone={tone} search={search}/></>}
    {module==='cosmetics'&&section==='nutrition'&&<><OptionCluster title="Concerns" options={unique(cosmetics.flatMap((item)=>item.concerns??[]))} value={listValue(draft,'concerns')} onChange={toggle('concerns')} tone={tone} search={search} defaultOpen/><details className="filter-accordion"><summary><span>Rating</span><small>range</small><ChevronDown size={14}/></summary><div className="accordion-content"><RangePair label="Rating" min={0} max={5} minKey="minRating" maxKey="maxRating" filters={draft} onChange={update}/></div></details></>}
    {module==='cosmetics'&&section==='goals'&&<><OptionCluster title="Storage location" options={locations.map((location)=>location.id)} labels={locationLabels} value={listValue(draft,'locationIds')} onChange={toggle('locationIds')} tone={tone} search={search}/><Field label="Ingredients contain"><input value={String(draft.ingredientsText??'')} onChange={(event)=>update('ingredientsText',event.target.value||undefined)} placeholder="e.g. niacinamide"/></Field></>}
    {module==='cosmetics'&&section==='advanced'&&<><div className="filter-section-title">Date ranges</div><DateRange label="Purchase date" prefix="purchase" filters={draft} onChange={update}/><DateRange label="MFG date" prefix="mfg" filters={draft} onChange={update}/><DateRange label="Expiry date" prefix="expiry" filters={draft} onChange={update}/></>}
  </div><div className="saved-filters"><div className="filter-section-title"><Bookmark size={15}/> Save this combination</div><div className="save-filter-row"><input value={saveName} onChange={(event)=>setSaveName(event.target.value)} placeholder="e.g. Summer coolers"/><Button size="sm" variant="soft" onClick={()=>{if(saveName.trim()){onSave(saveName.trim(),draft);setSaveName('')}}}><Save size={14}/> Save</Button></div>{saved.length>0&&<div className="saved-list">{saved.map((item)=><div className="saved-item" key={item.id}><span>{item.name}</span><button type="button" onClick={()=>onUseSaved(item)}>Use</button><button type="button" className="danger-icon" onClick={()=>onDeleteSaved(item.id)} aria-label={`Delete ${item.name}`}><Trash2 size={14}/></button></div>)}</div>}</div><div className="filter-footer-sticky"><Button variant="ghost" onClick={()=>setDraft({})}><RotateCcw size={15}/> Reset</Button><Button onClick={()=>onApply(draft)}>Show results <ChevronDown size={15}/></Button></div></Modal>;
}
